### PR TITLE
Added about us page

### PR DESCRIPTION
**Pull request by PeterBell**

### CODE REVIEW

**Comment by debbhad** [comment]
Can you please change this?

**Comment by cemyilmaz1** [comment]
Please add a photo.

**Comment by PeterBell** [comment]
Hey @debbhad what specifically do you want changed?

**Comment by PeterBell** [comment]
Hey @cemyilmaz1 good idea, but I'm way too lazy for that

**Comment by nelson7787** [comment]
Can you add team member profiles?

**Comment by PeterBell** [comment]
How about I add a phone number?

**Comment by debbhad** [comment]
@PeterBell maybe we should add some photos here!

**Comment by PeterBell** [comment]
Hey @ebbhad do you think we're OK with just a phone number?

**Comment by PeterBell** [comment]
:+1:

**Comment by cemyilmaz1** [comment]
:+1

**Comment by debbhad** [comment]
:+1: looks great!

**Comment by cemyilmaz1** [comment]
:+1: @PeterBell

**Pull request merged**
